/**
 * This file contains text data for the cards.
 * source: https://en.wikipedia.org/wiki/Venus
 */

const cardsTitles = [
    'Venus',
    'Physical characteristics',
    'Geography',
    'Orbit and\&nbsp;rotation',
    'Observability'
];

const cardsContents = [
    'Venus is the second planet from the Sun. It is named after the Roman goddess of love and beauty. As the brightest natural object in Earth\'s night sky after the Moon, Venus can cast shadows and can be, on rare occasions, visible to the naked eye in broad daylight. Venus lies within Earth\'s orbit, and so never appears to venture far from the Sun, either setting in the west just after dusk or rising in the east a little while before dawn. Venus orbits the Sun every 224.7 Earth days. It has a synodic day length of 117 Earth days and a sidereal rotation period of 243 Earth days. As a consequence, it takes longer to rotate about its axis than any other planet in the Solar System, and does so in the opposite direction to all but Uranus. This means the Sun rises in the west and sets in the east. Venus does not have any moons, a distinction it shares only with Mercury among the planets in the Solar System. Venus is a terrestrial planet and is sometimes called Earth\'s "sister planet" because of their similar size, mass, proximity to the Sun, and bulk composition. It is radically different from Earth in other respects. It has the densest atmosphere of the four terrestrial planets, consisting of more than 96% carbon dioxide. The atmospheric pressure at the planet\'s surface is about 92 times the sea level pressure of Earth, or roughly the pressure at 900 m (3,000 ft) underwater on Earth. Even though Mercury is closer to the Sun, Venus has the hottest surface of any planet in the Solar System, with a mean temperature of 737 K (464 °C; 867 °F). Venus is shrouded by an opaque layer of highly reflective clouds of sulfuric acid, preventing its surface from being seen from space in visible light. It may have had water oceans in the past, but these would have vaporized as the temperature rose under a runaway greenhouse effect. The water has probably photodissociated, and the free hydrogen has been swept into interplanetary space by the solar wind because of the lack of a planetary magnetic field.',
    'Venus is one of the four terrestrial planets in the Solar System, meaning that it is a rocky body like Earth. It is similar to Earth in size and mass, and is often described as Earth\'s "sister" or "twin". The diameter of Venus is 12,103.6 km (7,520.8 mi)—only 638.4 km (396.7 mi) less than Earth\'s—and its mass is 81.5% of Earth\'s. Conditions on the Venusian surface differ radically from those on Earth because its dense atmosphere is 96.5% carbon dioxide, with most of the remaining 3.5% being nitrogen. The surface pressure is 9.3 megapascals (93 bar) and the surface temperature is 737 K (464 °C; 867 °F), above the critical points of both major constituents and making the surface atmosphere a supercritical fluid. Venus has an extremely dense atmosphere composed of 96.5% carbon dioxide, 3.5% nitrogen—both exist as supercritical fluids at the planet\'s surface—and traces of other gases including sulfur dioxide. The mass of its atmosphere is 92 times that of Earth\'s, whereas the pressure at its surface is about 93 times that at Earth\'s—a pressure equivalent to that at a depth of nearly 1 km (5⁄8 mi) under Earth\'s oceans. The density at the surface is 65 kg/m3, 6.5% that of water or 50 times as dense as Earth\'s atmosphere at 293 K (20 °C; 68 °F) at sea level. The CO2-rich atmosphere generates the strongest greenhouse effect in the Solar System, creating surface temperatures of at least 735 K (462 °C; 864 °F). This makes Venus\'s surface hotter than Mercury\'s, which has a minimum surface temperature of 53 K (−220 °C; −364 °F) and maximum surface temperature of 700 K (427 °C; 801 °F), even though Venus is nearly twice Mercury\'s distance from the Sun and thus receives only 25% of Mercury\'s solar irradiance. Because of its runaway greenhouse effect, Venus been identified by scientists such as Carl Sagan as a warning and research object linked to climate change on Earth.',
    'The Venusian surface was a subject of speculation until some of its secrets were revealed by planetary science in the 20th century. Venera landers in 1975 and 1982 returned images of a surface covered in sediment and relatively angular rocks. The surface was mapped in detail by Magellan in 1990–91. The ground shows evidence of extensive volcanism, and the sulfur in the atmosphere may indicate that there have been recent eruptions. About 80% of the Venusian surface is covered by smooth, volcanic plains, consisting of 70% plains with wrinkle ridges and 10% smooth or lobate plains. Two highland "continents" make up the rest of its surface area, one lying in the planet\'s northern hemisphere and the other just south of the equator. The northern continent is called Ishtar Terra after Ishtar, the Babylonian goddess of love, and is about the size of Australia. Maxwell Montes, the highest mountain on Venus, lies on Ishtar Terra. Its peak is 11 km (7 mi) above the Venusian average surface elevation. The southern continent is called Aphrodite Terra, after the Greek goddess of love, and is the larger of the two highland regions at roughly the size of South America. A network of fractures and faults covers much of this area.',
    'Venus orbits the Sun at an average distance of about 0.72 AU (108 million km; 67 million mi), and completes an orbit every 224.7 days. Although all planetary orbits are elliptical, Venus\'s orbit is currently the closest to circular, with an eccentricity of less than 0.01. Simulations of the early solar system orbital dynamics have shown that the eccentricity of the Venus orbit may have been substantially larger in the past, reaching values as high as 0.31 and possibly impacting the early climate evolution. All the planets in the Solar System orbit the Sun in an anticlockwise direction as viewed from above Earth\'s north pole. Most planets also rotate on their axes in an anti-clockwise direction, but Venus rotates clockwise in retrograde rotation once every 243 Earth days—the slowest rotation of any planet. Because its rotation is so slow, Venus is very close to spherical. A Venusian sidereal day thus lasts longer than a Venusian year (243 versus 224.7 Earth days). Venus\'s equator rotates at 6.52 km/h (4.05 mph), whereas Earth\'s rotates at 1,674.4 km/h (1,040.4 mph). Venus\'s rotation period measured with Magellan spacecraft data over a 500-day period is smaller than the rotation period measured during the 16-year period between the Magellan spacecraft and Venus Express visits, with a difference of about 6.5 minutes. Because of the retrograde rotation, the length of a solar day on Venus is significantly shorter than the sidereal day, at 116.75 Earth days (making the Venusian solar day shorter than Mercury\'s 176 Earth days — the 116-day figure is extremely close to the average number of days it takes Mercury to slip underneath the Earth in its orbit). One Venusian year is about 1.92 Venusian solar days. To an observer on the surface of Venus, the Sun would rise in the west and set in the east, although Venus\'s opaque clouds prevent observing the Sun from the planet\'s surface.',
    'To the naked eye, Venus appears as a white point of light brighter than any other planet or star (apart from the Sun). The planet\'s mean apparent magnitude is −4.14 with a standard deviation of 0.31. The brightest magnitude occurs during crescent phase about one month before or after inferior conjunction. Venus fades to about magnitude −3 when it is backlit by the Sun. The planet is bright enough to be seen in broad daylight, but is more easily visible when the Sun is low on the horizon or setting. As an inferior planet, it always lies within about 47° of the Sun. Venus "overtakes" Earth every 584 days as it orbits the Sun. As it does so, it changes from the "Evening Star", visible after sunset, to the "Morning Star", visible before sunrise. Although Mercury, the other inferior planet, reaches a maximum elongation of only 28° and is often difficult to discern in twilight, Venus is hard to miss when it is at its brightest. Its greater maximum elongation means it is visible in dark skies long after sunset. As the brightest point-like object in the sky, Venus is a commonly misreported "unidentified flying object".'
];
